config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "home/help"
  get "posts/index"
  root "home#index"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :body
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :body
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    if @comment.save
      redirect_to @post, notice: "Comment  foi  criado  com  sucesso!"
    else
      redirect_to @post
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.save
    redirect_to @post
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to @post
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path,
        notice: "Post was sucessfully created !"
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path,
        notice: "Post was sucessfully update !"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path,
        notice: "Post was sucessfully removed !"
    else
      redirect_to posts_path,
        alert: "Fail to remove post !"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def preenche_titulo(titulo_da_pagina = ’’)
    titulo_padrao = "Blog  App"
    if (titulo_da_pagina.empty?)
      titulo_padrao
    else
      "#{titulo_da_pagina} | #{titulo_padrao}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/help.html.erb
<%= provide :titulo , "Help" %>
<div >
  <h1>Blog App </h1>
  <p>
    Esta e a pagina  de  ajuda  da  aplicacao  Blog  desenvolvida  durante o Laboratorio  de  Engenharia  de  Software.
  </p>
</div >

app/views/home/index.html.erb
<%= provide :titulo , "Home" %>
<div class=" center jumbotron ">
  <h1 > Microblog </h1 >
  <p>
    Esta e a pagina principal da ¸aplicação Blog desenvolvida durante o Laboratorio de Engenharia de Software .
  </p>
  <%= link_to "Posts", posts_path , class: "btn btn-lg btn-primary" %>
</div >

app/views/layouts/application.html.erb
<!DOCTYPE html >
<html >
  <head >
    <title> <%= preenche_titulo(yield(:titulo)) %> </title >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true%>
    <%= csrf_meta_tags %>
  </head >
  <body >
    <nav class=" navbar navbar-expand-md navbar-dark bg-dark ">
      <%=link_to "Blog", "#", id: "logo", class: "navbar-brand" %>
      <ul class=" navbar-nav ">
        <li class="nav-item ">
          <%=link_to " Home ", home_index_path , class:"nav-link " %>
        </li >
        <li class="nav-item ">
          <%= link_to " Help " , home_help_path , class:"nav-link " %>
        </li >
      </ul >
    </nav >
    <div class=" container ">
      <%=yield %>
    </div >
  </body >
</html >

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Request failed ! </h4>
    <ul >
      <% @post.errors.full_messages.each do |message| %>
        <li> <%=message %> </li >
      <%end %>
    </ul >
    <hr >
    <p class ="mb -0">Please , correct issues and try again . </p>
  </div >
<% end %>
<div class="card">
  <%= form_with model: @post , local: true do |form| %>
    <div class="card-body ">
      <div class="form-group">
        <%= form.label :title %> <br>
        <%= form.text_field :title , class: 'form-control' %>
      </div >
      <div class="form-group">
        <%= form.label :body %> <br >
        <%= form.text_area :body , class: 'form-control', rows: 5 %>
      </div >
      <div class="form-group text-right">
        <%= link_to 'Back', posts_path , class: 'btn btn-outline-secondary' %>
        <%= form.submit "Save", class: 'btn btn-primary'%>
      </div >
    </div >
  <% end %>
</div >

app/views/posts/edit.html.erb
<h1>Edit Post </h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= provide :titulo , "Posts" %>
<div class ="table-responsive-md">
  <h2 >Posts </h2 >
  <%if flash[:notice] %>
    <div id="notice" class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div >
  <% end %>
  <%if flash[:alert] %>
    <div id="alert" class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div >
  <% end %>
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col" width ="30%">Title </th >
        <th scope="col" width ="45%">Body </th >
        <th scope="col" width ="25%"></th >
      </tr>
    </thead >
    <tbody >
      <% @posts.each do | post | %>
        <tr >
          <td > <%= post.title %> </td >
          <td > <%= post.body %> </td >
          <td > <%= link_to 'Show', post , class: 'btn btn-info' %>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning' %>
            <%= link_to 'Delete', post , method: :delete , data: { confirm: 'Tem certeza ?' }, class: 'btn btn-danger' %> </td >
        </tr >
      <% end %>
    </tbody >
  </table >
  <%= link_to 'New Post', new_post_path , class: 'btn btn-success ' %>
</div >

app/views/posts/new.html.erb
<h1>Novo Post </h1>
<%= form_with scope: :post , url: posts_path , local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h2 > <%= @post.title %> </h2 >
  <span class="label label-primary">
    Last update <%= @post.updated_at.strftime ("%b %d, %Y") %>
  </span >
</div >
<div class ="panel panel-default">
  <div class ="panel-body">
    <p>
      <%= @post.body %>
      ...
    </p>
  </div >
  <h3> Comments </h3>
  <div id="comments">
    <% @post.comments.each do |comment| %>
      <p>
        <strong >
          Posted <%= time_ago_in_words(comment.created_at) %>
        </strong>
        <%= h(comment.body)%>
      </p>
    <% end %>
  </div >
  <div class =" card ">
    <%= form_for([@post,Comment.new]) do |f| %>
      <div class="card-body">
        <div class="form-group">
          <%= f.label :body , "New Comment" %> <br>
          <%= f.text_area :body, class: 'form-control', rows: 5 %>
        </div>
        <div class="form-group">
          <%= f.submit "Add Comments" , class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div >
  <br/>
  <div class="text-right">
    <%= link_to 'Back', posts_path , class: 'btn btn-outline-secondary' %>
  </div >
</div >